/* =========================================================
   MODIFIE UNIQUEMENT CETTE PARTIE POUR PERSONNALISER LE SITE
========================================================= */
const RELATIONSHIP={person1:'Préga',person2:'Tchelsy',startDate:'2022-09-15T00:00:00',photo:'images/couple.jpg'};
const BIRTHDAYS=[
{id:1,name:'Tchelsy',birthDate:'2002-05-18',birthdayTime:'00:00',photo:'images/tchelsy.jpg',giftTitle:'Un cadeau pour mon amour ❤️',letterTitle:'Pour toi, mon amour ❤️',letter:'Mon amour,\n\nAujourd’hui est une journée très spéciale. Je veux te rappeler à quel point tu es importante pour moi. ❤️\n\nMerci pour tous les moments que nous partageons. Je te souhaite beaucoup de bonheur, de réussite, de paix et d’amour.\n\nJoyeux anniversaire mon amour. ❤️'},
{id:2,name:'Préga',birthDate:'2001-10-10',birthdayTime:'00:00',photo:'images/prega.jpg',giftTitle:'Une surprise pour toi 🎁',letterTitle:'Joyeux anniversaire ❤️',letter:'Mon amour,\n\nAujourd’hui c’est ton jour. ❤️\n\nQue cette nouvelle année de ta vie soit remplie de bonheur, de réussite et de beaux projets.\n\nProfite pleinement de cette journée.\n\nJoyeux anniversaire à toi. ❤️'}
];
const $=s=>document.querySelector(s);
function localDate(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function birthdayDate(e,y){const [m,d]=e.birthDate.split('-').slice(1).map(Number),[h,min]=e.birthdayTime.split(':').map(Number);let day=d;if(m===2&&d===29&&!((y%4===0&&y%100!==0)||y%400===0))day=28;return new Date(y,m-1,day,h,min,0,0)}
function currentBirthday(e,n){return birthdayDate(e,n.getFullYear())}
function unlocked(e,n){return n>=currentBirthday(e,n)}
function nextBirthday(e,n){let d=currentBirthday(e,n);if(n>=d)d=birthdayDate(e,n.getFullYear()+1);return d}
function age(e,y){return y-Number(e.birthDate.slice(0,4))}
function fmt(d){return new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(d)}
function relationshipDuration(start,now){let years=now.getFullYear()-start.getFullYear();let ann=new Date(start.getFullYear()+years,start.getMonth(),start.getDate(),start.getHours(),start.getMinutes(),start.getSeconds());if(ann>now){years--;ann=new Date(start.getFullYear()+years,start.getMonth(),start.getDate(),start.getHours(),start.getMinutes(),start.getSeconds())}let r=now-ann;const day=86400000,hour=3600000,min=60000;const days=Math.floor(r/day);r%=day;const hours=Math.floor(r/hour);r%=hour;const minutes=Math.floor(r/min);r%=min;const seconds=Math.floor(r/1000);return{years,days,hours,minutes,seconds}}
function totalMonths(start,now){let m=(now.getFullYear()-start.getFullYear())*12+now.getMonth()-start.getMonth();if(now.getDate()<start.getDate())m--;return Math.max(0,m)}
function updateRelationship(){const start=new Date(RELATIONSHIP.startDate),now=new Date();if(isNaN(start)){console.error('startDate invalide');return}if(now<start){['relYears','relMonths','relDays','relHours','relMinutes','relSeconds'].forEach(id=>$('#'+id).textContent='0');return}const d=relationshipDuration(start,now);$('#relYears').textContent=d.years;$('#relMonths').textContent=totalMonths(start,now);$('#relDays').textContent=d.days;$('#relHours').textContent=String(d.hours).padStart(2,'0');$('#relMinutes').textContent=String(d.minutes).padStart(2,'0');$('#relSeconds').textContent=String(d.seconds).padStart(2,'0')}
function renderRelationship(){const names=`${RELATIONSHIP.person1} & ${RELATIONSHIP.person2}`;$('#heroNames').textContent=names;$('#coupleNames').textContent=names;$('#footerNames').textContent=names;$('#relationshipDateText').textContent=`Depuis le ${fmt(new Date(RELATIONSHIP.startDate))}`;$('#couplePhoto').src=RELATIONSHIP.photo}
function renderBirthdays(){const grid=$('#eventsGrid');grid.innerHTML='';const y=new Date().getFullYear();BIRTHDAYS.forEach(e=>{const c=document.createElement('article');c.className='birthday';c.dataset.eventId=e.id;c.innerHTML=`<div class="person"><img src="${e.photo}" alt="${e.name}"><div><h3>${e.name}</h3><p>Né(e) le ${fmt(localDate(e.birthDate))}</p><p class="age">🎂 ${age(e,y)} ans cette année</p></div></div><p class="label">Prochain anniversaire</p><div class="countdown">Chargement...</div><p class="status">🎁 Ton cadeau est encore verrouillé.</p><button class="btn giftbtn" data-gift-id="${e.id}">Ouvrir mon cadeau 🎁</button>`;grid.appendChild(c)});updateBirthdays()}
function updateBirthdays(){const now=new Date();BIRTHDAYS.forEach(e=>{const c=document.querySelector(`[data-event-id="${e.id}"]`);if(!c)return;const cd=c.querySelector('.countdown'),status=c.querySelector('.status'),btn=c.querySelector('.giftbtn');if(unlocked(e,now)){cd.innerHTML='<div class="today">🎂 C’est aujourd’hui ! ❤️</div>';status.textContent='🎁 Ton cadeau est maintenant disponible !';btn.style.display='inline-flex';return}const diff=Math.max(0,nextBirthday(e,now)-now),days=Math.floor(diff/86400000),hours=Math.floor(diff%86400000/3600000),minutes=Math.floor(diff%3600000/60000),seconds=Math.floor(diff%60000/1000);cd.innerHTML=`<div><b>${days}</b><small>Jours</small></div><div><b>${String(hours).padStart(2,'0')}</b><small>Heures</small></div><div><b>${String(minutes).padStart(2,'0')}</b><small>Minutes</small></div><div><b>${String(seconds).padStart(2,'0')}</b><small>Secondes</small></div>`;status.textContent='🎁 Ton cadeau est encore verrouillé.';btn.style.display='none'})}
let selected=null;function openModal(e){selected=e;$('#giftTitle').textContent=e.giftTitle;$('#letterTitle').textContent=e.letterTitle;$('#letterText').textContent=e.letter;$('#giftStage').hidden=false;$('#letterStage').hidden=true;$('.gift').classList.remove('opened');$('#giftModal').classList.add('active');document.body.style.overflow='hidden'}function closeModal(){$('#giftModal').classList.remove('active');document.body.style.overflow=''}function reveal(){if(!selected)return;$('.gift').classList.add('opened');setTimeout(()=>{$('#giftStage').hidden=true;$('#letterStage').hidden=false;confetti()},900)}function confetti(){const canvas=$('#confettiCanvas'),ctx=canvas.getContext('2d');canvas.width=innerWidth;canvas.height=innerHeight;const p=Array.from({length:100},()=>({x:Math.random()*canvas.width,y:-20-Math.random()*canvas.height,s:12+Math.random()*12,v:2+Math.random()*4,r:Math.random()*6}));let t=performance.now();function draw(now){ctx.clearRect(0,0,canvas.width,canvas.height);p.forEach(x=>{x.y+=x.v;x.r+=.05;ctx.save();ctx.translate(x.x,x.y);ctx.rotate(x.r);ctx.font=`${x.s}px serif`;ctx.fillText(['❤️','💕','💖','✨'][Math.floor(Math.random()*4)],0,0);ctx.restore()});if(now-t<5000)requestAnimationFrame(draw)}requestAnimationFrame(draw)}
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-gift-id]');if(!b)return;const e=BIRTHDAYS.find(x=>x.id===Number(b.dataset.giftId));if(e&&unlocked(e,new Date()))openModal(e)});$('#openGift').addEventListener('click',reveal);$('#closeGift').addEventListener('click',closeModal);$('.overlay').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function init(){renderRelationship();renderBirthdays();updateRelationship();updateBirthdays();setInterval(()=>{updateRelationship();updateBirthdays()},1000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
